### ISSUE TITLE
Installation funktioniert nur bei korrektem Plugin-Verzeichnis

### ISSUE THREAD

**Issue by ghost** [RRZE-Webteam/rrze-rsvp-network#6]
Die Installation dieses Plugins funktioniert nur, falls das Verzeichnis des `rrze-rsvp` Plugins entsprechend heißt. Wird das `rrze-rsvp` Plugin mit einer zip-Datei installiert die anders benannt ist (z.B. download des aktuellen `master` von GitHub als zip erzeugt `rrze-rsvp-master.zip`), übernimmt Wordpress diese Bezeichnung und die Installation von `rrze-rsvp-network` schlägt fehl mit dem Hinweis, `rrze-rsvp` sei nicht installiert. Hier wäre ein entsprechender Hinweis gut.

**Comment by thenickless** [comment]
Danke für die Anregung. Der Hinweis ist nun ergänzt um die korrekte Pfadangabe zum rrze-rsvp Plugin
